from utilities import *

if len(sys.argv) == 3:
	data = setupData(sys.argv[1])

	modelFile = open(sys.argv[2], 'r')
	model = pickle.load(modelFile)

	classify_maxent(model, data)

else:
	print "Useage: python test.py dataFile modelFile"
	print "    Where <dataFile> is the name of a context file generated by  Contextualizer,"
	print "    and <modelFile> is the name of the saved model file"
