from utilities import *

if len(sys.argv) == 3:
	trainingData = setupData(sys.argv[1])
	model = train_maxent(trainingData)
	outputModel = open(sys.argv[2], 'w')
	pickle.dump(model, outputModel)

else:
	print "Usage: python train.py <trainFile> <nameOfModel>"
	print "    Where <trainFile> is the path to a context file generated by",
	print "Contextualizer."
	print "    and <nameOfModel> is the path to save the generated model to."
